json.id user.id
json.name user.name
json.email user.email
json.username user.username
json.street_1 user.street_1
json.street_2 user.street_2
json.city user.city
json.state user.state
json.postal_code user.postal_code
json.country user.country